### ISSUE TITLE
Update PyPI metadata and tag releases on GitHub

### ISSUE THREAD

**Issue by Zac-HD** [hchasestevens/hypothesis-protobuf#5]
I was looking [at libraries.io](https://libraries.io/pypi/hypothesis/dependents) and noticed that `hypothesis-pb` didn't appear in the list - though it's certainly on PyPI and should have a declared dependency.

- Can you please upload a new version which does depend on Hypothesis, as `setup.py` currently does?
- Providing the `long_description` tag would also be great - PyPI now support GH-flavored markdown, so you could just use the contents of `README.md` 😄 
- Apparently the latest release on PyPI was not using the latest commit in this repo.  Could you also document what's going on there and/or fix it and/or tag your releases on Github?

Thanks!

**Comment by Zac-HD** [comment]
#### Add `Framework :: Hypothesis` PyPI trove classifier

The Python Packaging Authority has recently created a new trove classifier to help users find Hypothesis-related packages, as described and demonstrated in HypothesisWorks/hypothesis#1663.

It would be great if this package used it too!

**Comment by hchasestevens** [comment]
Hi @Zac-HD , this should be fixed now. Thanks for the contribution!
